# Netlify konfigurasjon for Urso Blazor WebAssembly
[build]
  # Bygger Blazor WebAssembly til wwwroot/
  command = "dotnet publish src/Frontend -c Release -o dist --nologo"
  # Deploy mappen som inneholder den statiske nettsiden
  publish = "dist/wwwroot"

[build.environment]
  # Spesifiserer .NET versjon
  DOTNET_VERSION = "10.0"

# SPA rewrite for Blazor routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets
[[headers]]
  for = "/_framework/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/wasm"

[[headers]]
  for = "/*.dll"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; script-src 'self' 'unsafe-eval'"
